[local]
localhost

[mongodb]
mongodb.gssc.online

[mysql]
mysql.gssc.online

[redis]
redis.gssc.online

[rabbitmq]
rabbitmq.gssc.online

[catalogue]
catalogue.gssc.online

[user]
user.gssc.online

[cart]
cart.gssc.online

[shipping]
shipping.gssc.online

[payment]
payment.gssc.online

[frontend]
frontend.gssc.online